// Navne skal matche API'ets "name" felt 1:1
export const LEAGUE_WHITELIST_NAMES = [
  "England - Premier League",
  "Spain - La Liga",
  "Germany - Bundesliga",
  "Italy - Serie A",
  "France - Ligue 1",
  "Netherlands - Eredivisie",
  "Belgium - Pro League",
  "Turkey - Super League",
  "Portugal - Primeira Liga",
  "Denmark - Superliga",
  "Denmark - 2nd Division",
  "Denmark - Division 1",
  "Sweden - Allsvenskan",
  "Norway - Eliteserien",
  "USA - Major League Soccer",
  "Mexico - Liga MX",
  "Brazil - Serie A",
  "England - EFL Cup",
  "Germany - Cup",
  "UEFA - Champions League",
  "FIFA - World Cup Qualifiers Africa",
  "FIFA - World Cup Qualifiers CONCACAF",
  "FIFA - World Cup Qualifiers Europe",
  "UEFA - U21 Euro Championship Qualifiers",
  "FIFA - World Cup Qualifiers South America",
  "International Clubs - UEFA Europa League",
  "International Clubs - UEFA Conference League",
];
